version: "3.8"

services:
  ela_1:
    build: ela_1
    container_name: ela_1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - ./ela_1/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./ela_1/user_dict.txt:/usr/share/elasticsearch/config/user_dict.txt
    ports:
      - "9200:9200"
    networks:
      - common

volumes:
  elasticsearch-data:
    driver: local

networks:
  common:
    driver: bridge
